### ISSUE TITLE
Deploy on docker

### ISSUE THREAD

**Issue by fengmk2** [X-Profiler/all-in-one#1]
参考 https://github.com/cnpm/cnpmcore/pull/509 默认支持 docker 部署，让 sre 可以快速部署。

**Comment by fengmk2** [comment]
这周我会搞定一个版本，然后部署一个免费的 demo 示例出来让大家本地使用。

**Comment by fengmk2** [comment]
@hyj1991 X-Profiler 邀请一下我？

**Comment by hyj1991** [comment]
> @hyj1991 X-Profiler 邀请一下我？

你在 Organization 里面呀，我调整你为 owner 了
