### ISSUE TITLE
关于默认存储

### ISSUE THREAD

**Issue by defp** [X-Profiler/all-in-one#5]
https://www.yuque.com/hyj1991/easy-monitor/plugin-storage 

> 因此默认的 storage 模块仅能用于控制台单机部署或者本地开发下。

我没看到具体的文件路径配置在哪? 比如默认的存储位置, 比如我用docker 部署, 需要把目录 mount 到宿主机器

另外

![img_v3_026v_f6cd64a3-a687-4cf2-b868-89cb9d12eb5g](https://github.com/X-Profiler/all-in-one/assets/612381/2aaf62a2-b70a-4d03-aa5d-40a4d7b05940)

这个是不是缺失什么环境变量?

我绑定了域名, 浏览器中直接访问 是 127.0.0.1

**Comment by hyj1991** [comment]
仔细看文档的 console 配置说明

**Comment by defp** [comment]
应该是这个代码

https://github.com/X-Profiler/xprofiler-console/blob/master/lib/plugin/egg-xprofiler-storage/app.js

**Comment by defp** [comment]
https://github.com/X-Profiler/xprofiler-console/blob/master/lib/plugin/egg-xprofiler-storage/config/config.default.js 

  config.storagePath = path.join(appInfo.baseDir, 'profiler');

**Comment by defp** [comment]
安装上面代码中我搜索了文档

https://www.yuque.com/search?q=profiler&type=content&scope=hyj1991%2Feasy-monitor&tab=book&p=1&sence=modal

没看到相关说明

**Comment by defp** [comment]
通过代码 得到目录是
项目运行目录下 profiler 

对于官方提高的dockerfile

应该是 /usr/src/app/profiler
